// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/user/service.go

// Package mock is a generated GoMock package.
package mock

import (
	user "gilsaputro/dating-apps/internal/service/user"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserServiceMethod is a mock of UserServiceMethod interface.
type MockUserServiceMethod struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMethodMockRecorder
}

// MockUserServiceMethodMockRecorder is the mock recorder for MockUserServiceMethod.
type MockUserServiceMethodMockRecorder struct {
	mock *MockUserServiceMethod
}

// NewMockUserServiceMethod creates a new mock instance.
func NewMockUserServiceMethod(ctrl *gomock.Controller) *MockUserServiceMethod {
	mock := &MockUserServiceMethod{ctrl: ctrl}
	mock.recorder = &MockUserServiceMethodMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceMethod) EXPECT() *MockUserServiceMethodMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *MockUserServiceMethod) DeleteUser(arg0 user.DeleteUserServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMethodMockRecorder) DeleteUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserServiceMethod)(nil).DeleteUser), arg0)
}

// GetUserByID mocks base method.
func (m *MockUserServiceMethod) GetUserByID(arg0 user.GetByIDServiceRequest) (user.UserServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0)
	ret0, _ := ret[0].(user.UserServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServiceMethodMockRecorder) GetUserByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserServiceMethod)(nil).GetUserByID), arg0)
}

// UpdateUser mocks base method.
func (m *MockUserServiceMethod) UpdateUser(arg0 user.UpdateUserServiceRequest) (user.UserServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0)
	ret0, _ := ret[0].(user.UserServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceMethodMockRecorder) UpdateUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserServiceMethod)(nil).UpdateUser), arg0)
}

// UpgradeUser mocks base method.
func (m *MockUserServiceMethod) UpgradeUser(arg0 user.UpgradeServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradeUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpgradeUser indicates an expected call of UpgradeUser.
func (mr *MockUserServiceMethodMockRecorder) UpgradeUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeUser", reflect.TypeOf((*MockUserServiceMethod)(nil).UpgradeUser), arg0)
}
